ALTER TABLE alumnos
ADD COLUMN estado TINYINT(1) NOT NULL DEFAULT 1;

ALTER TABLE maestros
ADD COLUMN estado TINYINT(1) NOT NULL DEFAULT 1;

ALTER TABLE facultades
ADD COLUMN estado TINYINT(1) NOT NULL DEFAULT 1;

ALTER TABLE carreras
ADD COLUMN estado TINYINT(1) NOT NULL DEFAULT 1;

ALTER TABLE cursos
ADD COLUMN estado TINYINT(1) NOT NULL DEFAULT 1;

ALTER TABLE secciones
ADD COLUMN estado TINYINT(1) NOT NULL DEFAULT 1;

ALTER TABLE sedes
ADD COLUMN estado TINYINT(1) NOT NULL DEFAULT 1;

ALTER TABLE aulas
ADD COLUMN estado TINYINT(1) NOT NULL DEFAULT 1;

ALTER TABLE jornadas
ADD COLUMN estado TINYINT(1) NOT NULL DEFAULT 1;

ALTER TABLE asignacioncursosalumnos
ADD COLUMN estado TINYINT(1) NOT NULL DEFAULT 1;

ALTER TABLE asignacioncursosmastros
ADD COLUMN estado TINYINT(1) NOT NULL DEFAULT 1;
